version: '3'
services:
  atorin:
    build: .
    links:
    - mongo
    - influx
    depends_on:
      - influx
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: atorin
  influx:
    image: influxdb