version: '3'
services:
  atorin:
    image: liamdj23/atorin
    links:
    - mongo
    depends_on:
    - mongo
    volumes:
    - ./config.json:/app/config.json
    ports:
    - "8080:8080"
    restart: always
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: atorin
    ports:
    - "27017:27017"
    restart: always