version: '3'
services:
  atorin:
    build: .
    links:
    - mongo
    depends_on:
      - mongo
    ports:
    - "8080:8080"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: atorin