version: '3'
services:
  atorin:
    image: liamdj23/atorin
    links:
    - mongo
    depends_on:
      - mongo
    volumes:
    - ./config.json:/app/config.json
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: atorin