version: '3'
services:
  atorin:
    image: liamdj23/atorin
    links:
    - mongo
    - lavalink
    depends_on:
    - mongo
    - lavalink
    volumes:
    - ./config.json:/app/config.json
    - ../songs:/app/songs/
    ports:
    - "8080:8080"
    restart: always
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: atorin
    ports:
    - "27017:27017"
    restart: always
  lavalink:
    image: fredboat/lavalink:7ab68938
    ports:
    - "2333:2333"
    restart: always
