# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Atorin Discord Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make dependencies
        make config
        python -m pip install --upgrade pip distest
        pip install -r requirements.txt
    - name: Run bot
      run: |
        cd src
        sed -i 's/DISCORD_TOKEN/${{ secrets.DISCORD_TOKEN }}/g' settings/main.json
        nohup python main.py &
    - name: Test commands
      run: |
        python tests/test_commands.py -c ${{ secrets.CHANNEL_ID }} -r all ${{ secrets.BOT_ID }} ${{ secrets.TESTER_TOKEN }}