# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Atorin Discord Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip distest
        pip install -r requirements.txt
    - name: Run bot
      run: |
        TOKEN=${{ secrets.DISCORD_TOKEN }} nohup python src/main.py &
    - name: Test commands
      run: |
        sleep 5
        python tests/test_commands.py -c ${{ secrets.CHANNEL_ID }} -r all ${{ secrets.BOT_ID }} ${{ secrets.TESTER_TOKEN }}
    - name: Create package
      run: |
        pip install --user --upgrade setuptools wheel
        python setup.py sdist bdist_wheel
    - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Atorin
          path: |
            dist
