name: Atorin Discord Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install distest
      run: python -m pip install --upgrade pip distest
    - name: Fill config file
      run: |
        sed -i 's/DISCORD_TOKEN/${{ secrets.DISCORD_TOKEN }}/g' config.js
        sed -i 's/WEATHER_TOKEN/${{ secrets.OWM_TOKEN }}/g' config.js
    - name: Run Bot
      run: docker-compose up -d
    - name: Test commands
      run: python tests/test_commands.py -c ${{ secrets.CHANNEL_ID }} -r all ${{ secrets.BOT_ID }} ${{ secrets.TESTER_TOKEN }}